# GitHub Actions Documentation: https://docs.github.com/en/actions

name: "build"

on: ["pull_request", "push", "workflow_dispatch"]

# Cancels all previous workflow runs for the same branch that have not yet completed.
concurrency:
  # The concurrency group contains the workflow name and the branch name.
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  composer:
    name: "Check Composer"
    runs-on: "ubuntu-latest"
    steps:
      - name: "Checkout repository"
        uses: "actions/checkout@v2"
      - name: "Set up PHP"
        uses: "shivammathur/setup-php@v2"
        with:
          php-version: 7.4
          tools: composer-normalize
          coverage: none
      - name: "Run Composer normalize"
        run: "composer-normalize --dry-run"

  test:
    name: "Expect tests"
    runs-on: "ubuntu-latest"
    strategy:
      matrix:
        composer-version:
          - "v1"
          - "v2"
    steps:
      - name: "Checkout repository"
        uses: "actions/checkout@v2"
      - name: "Install expect"
        run: |
          sudo apt-get update
          sudo apt-get -y install expect
      - name: "Set up PHP"
        uses: "shivammathur/setup-php@v2"
        with:
          php-version: "latest"
          tools: "composer:${{ matrix.composer-version }}"
          coverage: "none"
      - name: "Run expect tests"
        run: "composer test"

  code-coverage:
    needs: test
    if: github.repository == 'ramsey/composer-install'
    name: "Code coverage"
    runs-on: "ubuntu-latest"
    steps:
      - name: "Checkout repository"
        uses: "actions/checkout@v2"
      - name: "Install expect"
        run: |
          sudo apt-get update
          sudo apt-get -y install expect
      - name: "Set up Ruby"
        uses: "ruby/setup-ruby@v1"
        with:
          ruby-version: "2.7"
      - name: "Install Ruby dependencies"
        run: |
          gem install bashcov
          gem install codecov
      - name: "Set up PHP"
        uses: "shivammathur/setup-php@v2"
        with:
          php-version: "latest"
          tools: "composer:v2"
          coverage: "none"
      - name: "Run expect tests"
        run: "bashcov --root ./bin -- ./tests/bash-test.sh tests/tests.sh"
      - name: "Publish coverage report to Codecov"
        uses: "codecov/codecov-action@v2"
        with:
          files: "./bin/coverage/codecov-result.json"

  static-analysis:
    name: "Static analysis"
    runs-on: "ubuntu-latest"
    steps:
      - name: "Checkout repository"
        uses: "actions/checkout@v2"
      - name: "Run shellcheck"
        run: "shellcheck --exclude=SC2230 bin/*.sh tests/*.sh"

  run:
    needs: test
    name: "Run action"
    runs-on: "${{ matrix.operating-system }}"
    strategy:
      matrix:
        operating-system:
          - "ubuntu-latest"
          - "windows-latest"
        dependency-versions:
          - "lowest"
          - "highest"
          - "locked"
        composer-version:
          - "v1"
          - "v2"
        composer-options:
          - "--ignore-platform-reqs"
          - ""
        working-directory:
          - "tests/fixtures/with-lock-file"
          - ""
        ignore-cache:
          - "yes"
          - ""
        custom-cache-key:
          - "my-super-custom-cache-key"
          - ""
    steps:
      - name: "Checkout repository"
        uses: "actions/checkout@v2"
      - name: "Set up PHP"
        uses: "shivammathur/setup-php@v2"
        with:
          php-version: "latest"
          tools: "composer:${{ matrix.composer-version }}"
          coverage: "none"
      - name: "Run composer-install action"
        uses: ./
        with:
          dependency-versions: "${{ matrix.dependency-versions }}"
          composer-options: "${{ matrix.composer-options }}"
          working-directory: "${{ matrix.working-directory }}"
          ignore-cache: "${{ matrix.ignore-cache }}"
          custom-cache-key: "${{ matrix.custom-cache-key }}"
