# GitHub Actions Documentation: https://docs.github.com/en/actions

name: "build"

on: ["pull_request", "push"]

jobs:
  test:
    name: "Expect Tests"
    runs-on: "ubuntu-latest"
    steps:
      - name: "Checkout repository"
        uses: "actions/checkout@v2"
      - name: "Install expect"
        run: |
          sudo apt-get update
          sudo apt-get -y install expect
      - name: "Set up PHP"
        uses: "shivammathur/setup-php@v2"
        with:
          php-version: "latest"
          tools: "composer:v2"
          coverage: "none"
      - name: "Run expect tests"
        run: "composer test"

  run:
    name: "Run Action"
    runs-on: "${{ matrix.operating-system }}"
    strategy:
      matrix:
        operating-system:
          - "ubuntu-latest"
          - "windows-latest"
        dependency-versions:
          - "lowest"
          - "highest"
          - "locked"
        composer-options:
          - "--ignore-platform-reqs"
          - ""
        working-directory:
          - "subdirectory"
          - ""
        ignore-cache:
          - "yes"
          - ""
        custom-cache-key:
          - "my-super-custom-cache-key"
          - ""
    steps:
      - name: "Checkout repository"
        uses: "actions/checkout@v2"
      - name: "Set up PHP"
        uses: "shivammathur/setup-php@v2"
        with:
          php-version: "latest"
          tools: "composer:v2"
          coverage: "none"
      - name: "Run composer-install action"
        uses: ./
        with:
          dependency-versions: "${{ matrix.dependency-versions }}"
          composer-options: "${{ matrix.composer-options }}"
          working-directory: "${{ matrix.working-directory }}"
          ignore-cache: "${{ matrix.ignore-cache }}"
          custom-cache-key: "${{ matrix.custom-cache-key }}"
